#!/usr/bin/env node
/**
 * stack.mjs — tech-stack single-source generator + consistency gate.
 *
 * CANONICAL SOURCE: mcp-workspace/tools/scripts/stack.mjs — keep the copies in
 * nowiro/mcp-alm and nowiro/mcp-devtools in sync with this file. See docs/tech-stack.md.
 *
 *   node stack.mjs sync   — regenerate the <!-- stack:auto --> block in every target file
 *                           from package.json (+ .nvmrc) + docs/tech-stack.json curation.
 *   node stack.mjs check  — fail if any target block is stale (→ run sync), or if engines.node /
 *                           packageManager / .nvmrc are missing or .nvmrc is below the engines floor.
 *
 * One place to edit per concern: versions live in package.json / .nvmrc (the real source);
 * curated facts (which deps to surface, IDE/OS, lint summary, notes) live in docs/tech-stack.json.
 * Nothing in prose drifts because the prose block is generated.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import process from 'node:process';

const ROOT = process.cwd();
const CONFIG = 'docs/tech-stack.json';
const END = '<!-- stack:auto:end -->';
const BLOCK_RE = /<!-- stack:auto:begin[\s\S]*?<!-- stack:auto:end -->/;
const DEFAULT_TARGETS = ['docs/tech-stack.md', '.github/copilot-instructions.md'];

const readJson = async (rel) => JSON.parse(await readFile(resolve(ROOT, rel), 'utf8'));

function depVersion(pkg, name) {
  const v = pkg.dependencies?.[name] ?? pkg.devDependencies?.[name];
  return v ? v.replace(/^[\^~]/, '') : null;
}

function versionParts(s) {
  const m = String(s).match(/(\d+)(?:\.(\d+))?(?:\.(\d+))?/);
  return m ? [Number(m[1]), Number(m[2] ?? 0), Number(m[3] ?? 0)] : null;
}

function cmpVer(a, b) {
  for (let i = 0; i < 3; i++) {
    const d = (a[i] ?? 0) - (b[i] ?? 0);
    if (d) return d;
  }
  return 0;
}

async function buildBlock() {
  const cfg = await readJson(CONFIG);
  const primary = cfg.primary ?? 'package.json';
  const pkg = await readJson(primary);
  const engines = pkg.engines?.node ?? '(brak)';
  const pm = pkg.packageManager ?? '(brak)';
  const nvmrc = existsSync(resolve(ROOT, '.nvmrc'))
    ? (await readFile(resolve(ROOT, '.nvmrc'), 'utf8')).trim()
    : '(brak)';

  const pkgCache = { [primary]: pkg };
  const parts = [];
  for (const item of cfg.surface ?? []) {
    const from = item.from ?? primary;
    pkgCache[from] = pkgCache[from] ?? (await readJson(from));
    parts.push(`**${item.name}:** \`${depVersion(pkgCache[from], item.key) ?? '?'}\``);
  }

  const lines = [`- **Runtime:** Node \`${engines}\` (\`.nvmrc\` \`${nvmrc}\`) · \`${pm}\``];
  if (parts.length) lines.push(`- ${parts.join(' · ')}`);
  if (cfg.lint) lines.push(`- **Lint/format:** ${cfg.lint}`);
  if (cfg.ide)
    lines.push(`- **IDE:** VS Code \`${cfg.ide.vscode}\` · IntelliJ \`${cfg.ide.intellij}\` — GitHub Copilot`);
  if (cfg.os) lines.push(`- **OS:** ${cfg.os.join(' · ')}`);

  const begin = `<!-- stack:auto:begin — generated by \`npm run stack:sync\`; edit package.json / .nvmrc / docs/tech-stack.json, not here -->`;
  const block = `${begin}\n\n${lines.join('\n')}\n\n${END}`;
  return { cfg, block, engines, nvmrc, pm, primary };
}

async function sync() {
  const { cfg, block } = await buildBlock();
  const targets = cfg.targets ?? DEFAULT_TARGETS;
  let updated = 0;
  for (const t of targets) {
    const abs = resolve(ROOT, t);
    if (!existsSync(abs)) {
      console.error(`  ✗ target missing: ${t}`);
      process.exitCode = 1;
      continue;
    }
    const text = await readFile(abs, 'utf8');
    if (!BLOCK_RE.test(text)) {
      console.error(`  ✗ ${t}: no <!-- stack:auto:begin … end --> markers`);
      process.exitCode = 1;
      continue;
    }
    const next = text.replace(BLOCK_RE, block);
    if (next !== text) {
      await writeFile(abs, next, 'utf8');
      console.log(`  ✓ synced ${t}`);
      updated++;
    } else {
      console.log(`  = unchanged ${t}`);
    }
  }
  console.log(`stack:sync done — ${updated} file(s) updated`);
}

async function check() {
  const errors = [];
  const { cfg, block, engines, nvmrc, primary } = await buildBlock();
  const targets = cfg.targets ?? DEFAULT_TARGETS;
  for (const t of targets) {
    const abs = resolve(ROOT, t);
    if (!existsSync(abs)) {
      errors.push(`target missing: ${t}`);
      continue;
    }
    const m = (await readFile(abs, 'utf8')).match(BLOCK_RE);
    if (!m) errors.push(`${t}: no <!-- stack:auto --> markers (add them, then run npm run stack:sync)`);
    else if (m[0] !== block) errors.push(`${t}: stack block is stale — run \`npm run stack:sync\``);
  }
  if (engines === '(brak)') errors.push(`${primary}: missing engines.node`);
  if (nvmrc === '(brak)') errors.push(`.nvmrc missing`);
  const floor = engines !== '(brak)' ? versionParts(engines) : null;
  const nv = nvmrc !== '(brak)' ? versionParts(nvmrc) : null;
  if (floor && nv && cmpVer(nv, floor) < 0) errors.push(`.nvmrc (${nvmrc}) is below engines.node floor (${engines})`);

  if (errors.length) {
    console.error('✗ tech-stack check failed:');
    for (const e of errors) console.error(' - ' + e);
    process.exit(1);
  }
  console.log(`✓ tech-stack consistent — Node ${engines} (.nvmrc ${nvmrc}) · ${targets.length} target(s) in sync`);
}

const cmd = process.argv[2];
if (cmd === 'sync') await sync();
else if (cmd === 'check') await check();
else {
  console.error('usage: node tools/scripts/stack.mjs <sync|check>');
  process.exit(1);
}
